#!/usr/bin/env python3
"""Render kb/index.md from active KB entries."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: pip install -r requirements.txt") from exc


ROOT = Path(__file__).resolve().parents[1]
KB_ROOT = ROOT / "kb"
INDEX_PATH = KB_ROOT / "index.md"


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    _, frontmatter, _ = text.split("---\n", 2)
    return yaml.safe_load(frontmatter) or {}


def iter_entries() -> list[tuple[Path, dict]]:
    entries: list[tuple[Path, dict]] = []
    for path in sorted(KB_ROOT.rglob("*.md")):
        if path.name.startswith("_") or path == INDEX_PATH:
            continue
        if any(part.startswith("_") for part in path.relative_to(KB_ROOT).parts[:-1]):
            continue
        data = parse_frontmatter(path)
        if data.get("status") == "active":
            entries.append((path, data))
    return entries


def render() -> str:
    lines = [
        "# Boldr KB Index",
        "",
        "Generated by `python scripts/render_index.py`.",
        "",
    ]

    by_domain: dict[str, list[tuple[Path, dict]]] = {}
    for path, data in iter_entries():
        by_domain.setdefault(str(data.get("domain", "unknown")), []).append((path, data))

    for domain in sorted(by_domain):
        lines.extend([f"## {domain}", ""])
        rows = sorted(by_domain[domain], key=lambda item: item[1].get("slug", item[0].stem))
        for path, data in rows:
            rel = path.relative_to(ROOT)
            title = data.get("title") or data.get("slug") or path.stem
            lines.append(f"- [{title}](../{rel.as_posix()})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if kb/index.md is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not INDEX_PATH.exists() or INDEX_PATH.read_text() != rendered:
            print("kb/index.md is stale; run python scripts/render_index.py")
            return 1
        print("kb/index.md is current")
        return 0

    INDEX_PATH.write_text(rendered)
    print(f"wrote {INDEX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
